EDA

A continuación se realizará el análisis exploratorio de los datos.

In [1]:
#Librerias EDA
import pandas as pd
import numpy as np
import yaml
import os #sirve para interactuar con las rutas y carpetas del sistema operativo
import sys #para poder añadir la carpeta raíz del proyecto, ya que desde notebooks no se puede ver


# Cambia el directorio de trabajo a la raíz del proyecto
os.chdir("..")

# Agrega la raíz al sys.path para las importaciones
sys.path.append(os.getcwd())



with open("config/config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [ ]:
#Vista datos encuesta_soporte
encuesta_soporte_df = pd.read_excel(config['sources']['encuesta_soporte']['path'])
display(encuesta_soporte_df.head(10))

jira_df= pd.read_csv(config['sources']['jira']['path'])
display(jira_df.head(10))

#En el archivo Jira se identifica que la columna Clave de incidencia es el ID del ticket, por lo cual se realizará el cambio de nombre
#en la transformación para que se pueda utilizar como llave para unir ambas tablas.

,ID,Hora de inicio,Hora de finalización,Correo electrónico,Nombre,Total de puntos,Comentarios del cuestionario,Hora de publicación de la calificación,Nombre de la Compañía,Puntos: Nombre de la Compañía,...,Comentarios: ¿Cómo califica el tiempo de respuesta a la atención del ticket/solicitud reportado?,¿La solución entregada resolvió el problema reportado?,Puntos: ¿La solución entregada resolvió el problema reportado?,Comentarios: ¿La solución entregada resolvió el problema reportado?,¿Tienes alguna sugerencia que nos ayude a mejorar nuestros servicios?,Puntos: ¿Tienes alguna sugerencia que nos ayude a mejorar nuestros servicios?,Comentarios: ¿Tienes alguna sugerencia que nos ayude a mejorar nuestros servicios?,Seleccione el personal que atendió el ticket/solicitud,Puntos: Seleccione el personal que atendió el ticket/solicitud,Comentarios: Seleccione el personal que atendió el ticket/solicitud
0,929,2025-10-29 16:08:12,2025-10-29 16:09:37,anonymous,NaN,NaN,NaN,NaN,Integral de Empaques,NaN,...,NaN,"Si, completamente",NaN,NaN,Todo bien,NaN,NaN,Alan Ramírez,NaN,NaN
1,930,2025-10-30 18:41:58,2025-10-30 18:44:26,anonymous,NaN,NaN,NaN,NaN,Francisco A Rocha Alvarado SAS,NaN,...,NaN,Parcialmente,NaN,NaN,Servicio por parte de ustedes es pesimo,NaN,NaN,John Jairo Mamian,NaN,NaN
2,931,2025-11-04 13:07:21,2025-11-04 13:11:12,anonymous,NaN,NaN,NaN,NaN,colombina del cauca,NaN,...,NaN,"Si, completamente",NaN,NaN,darle una capitación virtual al personal que ...,NaN,NaN,Anthony Ospina,NaN,NaN
3,932,2025-11-04 14:26:03,2025-11-04 14:35:28,anonymous,NaN,NaN,NaN,NaN,Babú Palm S.A.S,NaN,...,NaN,"Si, completamente",NaN,NaN,Ninguna,NaN,NaN,Roberth Colonia,NaN,NaN
4,933,2025-11-06 08:01:16,2025-11-06 08:02:39,anonymous,NaN,NaN,NaN,NaN,Inversiones Eldorado SAS,NaN,...,NaN,"Si, completamente",NaN,NaN,Que el tiempo de respuesta de los ticket sea m...,NaN,NaN,Alan Ramírez,NaN,NaN
5,934,2025-11-06 16:57:53,2025-11-06 16:59:19,anonymous,NaN,NaN,NaN,NaN,Babú Palm,NaN,...,NaN,"Si, completamente",NaN,NaN,"Ninguna, excelente servicio",NaN,NaN,Roberth Colonia,NaN,NaN
6,935,2025-11-10 10:58:17,2025-11-10 11:01:53,anonymous,NaN,NaN,NaN,NaN,Extractora,NaN,...,NaN,"Si, completamente",NaN,NaN,"Bueno, que en algunos casos el tiempo de resp...",NaN,NaN,Alan Ramírez,NaN,NaN
7,936,2025-11-10 11:45:06,2025-11-10 11:47:17,anonymous,NaN,NaN,NaN,NaN,Espejos SAS,NaN,...,NaN,"Si, completamente",NaN,NaN,Ninguna,NaN,NaN,Alan Ramírez,NaN,NaN
8,937,2025-11-12 11:35:38,2025-11-12 11:47:20,anonymous,NaN,NaN,NaN,NaN,Manitoba.sas,NaN,...,NaN,"Si, completamente",NaN,NaN,No,NaN,NaN,Cindy Suárez,NaN,NaN
9,938,2025-11-12 11:49:02,2025-11-12 11:50:00,anonymous,NaN,NaN,NaN,NaN,Manitoba.sas,NaN,...,NaN,"Si, completamente",NaN,NaN,No,NaN,NaN,Brayan Calderón,NaN,NaN

,Tipo de Incidencia,Clave de incidencia,ID de la incidencia,Resumen,Etiquetas,Etiquetas.1,Etiquetas.2,Clave del proyecto,Nombre del proyecto,Tipo de proyecto,...,Prioridad,Creada,Fecha de vencimiento,Campo personalizado (Actual start),Campo personalizado (Actual start).1,Campo personalizado (Actual end),Campo personalizado (Actual end).1,Tiempo Trabajado,Campo personalizado (Razón),Campo personalizado (Razón).1
0,Informar sobre una incidencia,CAFQ-35,44378,"Solicitud prioritaria de análisis, causa raíz ...",NaN,NaN,NaN,CAFQ,CAFQ - CONTRATO SOPORTE DE SOFTWARE Hasta 01/1...,service_desk,...,Medium,04/sep/26 5:14 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Solicitud de correo electrónico,PROA-51,44376,Capacitación Filedesk Compras - Contabilidad,NaN,NaN,NaN,PROA,PROA - CONTRATO SOPORTE DE SOFTWARE Hasta 01/0...,service_desk,...,Medium,04/sep/26 5:12 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Solicitud de asistencia de [System],PSDI-2247,44374,PLX: Solicitud de configuración del Portal de ...,NaN,NaN,NaN,PSDI,PT - SOLICITUDES OPERACIONES,service_desk,...,Medium,04/sep/26 5:02 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Informar sobre una incidencia,MY-109,44372,Liquidación no paso al erp LCP 6599,SOPORTE,NaN,NaN,MY,MY - CONTRATO SOPORTE DE SOFTWARE TRACING Hast...,service_desk,...,High,04/sep/26 3:39 PM,07/sep/26 12:00 AM,NaN,NaN,NaN,NaN,NaN,ERP,NaN
4,Solicitud de asistencia de [System],PSDI-2246,44370,PCL - Actualización del ambiente productivo,INFRAESTRUCTURA,NaN,NaN,PSDI,PT - SOLICITUDES OPERACIONES,service_desk,...,Medium,04/sep/26 3:07 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Informar sobre una incidencia,ASM1-34,44367,Novedad en las marcaciones – Lector San Martín,SOPORTE,NaN,NaN,ASM1,ASM - CONTRATO SOPORTE DE SOFTWARE Hasta 30/01...,service_desk,...,High,04/sep/26 2:36 PM,07/sep/26 12:00 AM,NaN,NaN,NaN,NaN,NaN,MARCACIONES-CONEXION,NaN
6,Informar sobre una incidencia,UNQ-48,44365,Cambio de lector de tarjetas acceso portería,SOPORTE,NaN,NaN,UNQ,UNQ - CONTRATO SOPORTE DE SOFTWARE Hasta 07/12...,service_desk,...,Medium,04/sep/26 12:48 PM,07/sep/26 12:00 AM,NaN,NaN,NaN,NaN,NaN,DISPOSITIVO-DAÑO,NaN
7,Solicitud de asistencia de [System],PSDI-2244,44363,TREBOL - Solicitud de New York para el uso de ...,INFRAESTRUCTURA,NaN,NaN,PSDI,PT - SOLICITUDES OPERACIONES,service_desk,...,Medium,04/sep/26 11:52 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Informar sobre una incidencia,BYN-27,44361,asesoría sobre la configuración y creación de...,SOPORTE,NaN,NaN,BYN,BYN - CONTRATO SOPORTE DE SOFTWARE Hasta 28/02...,service_desk,...,Medium,04/sep/26 9:05 AM,08/sep/26 12:00 AM,NaN,NaN,NaN,NaN,NaN,DESCONCIMIENTO-SEGURIDAD,NaN
9,Informar sobre una incidencia,MXM-59,44359,CREACION DE UN CENTRO DE COSTOS Y ASOCIACION A EL,SOPORTE,NaN,NaN,MXM,MXM - CONTRATO SOPORTE DE SOFTWARE Hasta 19/07...,service_desk,...,Medium,04/sep/26 8:59 AM,07/sep/26 12:00 AM,NaN,NaN,NaN,NaN,NaN,DESCONOCIMIENTO- CENTRO DE COSTOS,NaN

In [ ]:
#Tipos de datos
print(jira_df.info(verbose=True))
print(encuesta_soporte_df.info(verbose=True))

#En el archivo Jira se identifican algunas columnas con datos nulos, algunas de ellas no se utilizaran puesto que no aportan valor
#para la visualización final. En la transformación solo se llevaran: "Clave de incidencia", "Tipo de Incidencia","ID de la incidencia",
#"Resumen","Etiquetas","Clave del proyecto", "Nombre del proyecto", "Campo personalizado (Organizations)", "Persona asignada", "Estado",
#"Prioridad", "Creada", "Fecha de vencimiento", "Campo personalizado (Actual start).1", "Campo personalizado (Actual end).1",
# "Campo personalizado (Razón)"

In [ ]:
#Tipos de datos
print(encuesta_soporte_df.info(verbose=True))
#En el archivo encuesta_soporte se identifican algunas columnas con datos nulos, algunas de ellas no se utilizaran puesto que no aportan valor
#para la visualización final. En la transformación solo se llevaran: "ID","Hora de inicio", "Hora de finalización", "Nombre de la Compañia",
#"Número de Ticket", "Seleccione el personal que atendió el ticket/solicitud" y las columnas con las 4 preguntas.

<class 'pandas.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 29 columns):
 #   Column                                                                                            Non-Null Count  Dtype
---  ------                                                                                            --------------  -----
 0   ID                                                                                                340 non-null    int64
 1   Hora de inicio                                                                                    340 non-null    datetime64[us]
 2   Hora de finalización                                                                              340 non-null    datetime64[us]
 3   Correo electrónico                                                                                340 non-null    str
 4   Nombre                                                                                            0 non-null      float64
 5   Total de puntos                                                                                   0 non-null      float64
 6   Comentarios del cuestionario                                                                      0 non-null      float64
 7   Hora de publicación de la calificación                                                            0 non-null      float64
 8   Nombre de la Compañía                                                                             340 non-null    str
 9   Puntos: Nombre de la Compañía                                                                     0 non-null      float64
 10  Comentarios: Nombre de la Compañía                                                                0 non-null      float64
 11  Número de Ticket                                                                                  340 non-null    str
 12  Puntos: Número de Ticket                                                                          0 non-null      float64
 13  Comentarios: Número de Ticket                                                                     0 non-null      float64
 14  ¿Cómo califica la atención y amabilidad del personal que lo atendió?                              340 non-null    int64
 15  Puntos: ¿Cómo califica la atención y amabilidad del personal que lo atendió?                      0 non-null      float64
 16  Comentarios: ¿Cómo califica la atención y amabilidad del personal que lo atendió?                 0 non-null      float64
 17  ¿Cómo califica el tiempo de respuesta a la atención del ticket/solicitud reportado?               340 non-null    str
 18  Puntos: ¿Cómo califica el tiempo de respuesta a la atención del ticket/solicitud reportado?       0 non-null      float64
 19  Comentarios: ¿Cómo califica el tiempo de respuesta a la atención del ticket/solicitud reportado?  0 non-null      float64
 20  ¿La solución entregada resolvió el problema reportado?                                            340 non-null    str
 21  Puntos: ¿La solución entregada resolvió el problema reportado?                                    0 non-null      float64
 22  Comentarios: ¿La solución entregada resolvió el problema reportado?                               0 non-null      float64
 23  ¿Tienes alguna sugerencia que nos ayude a mejorar nuestros servicios?                             329 non-null    str
 24  Puntos: ¿Tienes alguna sugerencia que nos ayude a mejorar nuestros servicios?                     0 non-null      float64
 25  Comentarios: ¿Tienes alguna sugerencia que nos ayude a mejorar nuestros servicios?                0 non-null      float64
 26  Seleccione el personal que atendió el ticket/solicitud                                            340 non-null    str
 27  Puntos: Seleccione el personal que atendió el ticket/solicitud                                    0 non-null      float64
 28  Comentarios: Seleccione el personal que atendió el ticket/solicitud                               0 non-null      float64
dtypes: datetime64[us](2), float64(18), int64(2), str(7)
memory usage: 77.2 KB
None

In [ ]:
#Revisión columna Nombre de la Compañía
#Se identifican nombres digitados diferentes pero que hacen referencia a la misma compañía
sorted(encuesta_soporte_df['Nombre de la Compañía'].unique())

['AGRICOLA COLOMBIANA',
 'AGRICOLA SANTA MARIA',
 'AGROHIERROS',
 'ALMACENES SI',
 'ARIGUANI',
 'Agropecuaria de Occidente',
 'Agropecuaria de Occidente sa',
 'Agrícola Colombiana SA',
 'Ahumados Toto SAs',
 'Almagrario',
 'Almagrario Logistics',
 'Amore Group SAS',
 'Antioquiagold',
 'Arrocera La Esmeralda ',
 'Auralac S.A',
 'BABUPALM IOL PRODUCS ZESE SAS',
 'BALL COLOMBIA',
 'BEISBOL DE COLOMBIA S.A.S',
 'BERHLAN DE COLOMBIA',
 'BHERLAN',
 'BIOD',
 'BIVIEN',
 'BLANCO Y NEGRO MASIVO',
 'Babupalm',
 'Babú Palm',
 'Babú Palm S.A.S',
 'Beisbol de Colombia S.A.S',
 'Beisbol de Colombia s.a.s',
 'Berhlan de Colombia',
 'Bgreen S.A.S',
 'Biod',
 'Bivien',
 'Blanco y Negro Masivo',
 'Blanco y negro masivo',
 'Blanco y negro masivo ',
 'Blanco y negro masivo sa',
 'BÉISBOL DE COLOMBIA SAS',
 'Béisbol de Colombia S.A.S',
 'CAFARCOL',
 'CAFE QUINDIO',
 'CAFE QUINDIO S.A.S ',
 'CAFE QUINDIO SAS',
 'CAFÉ QUINDIO',
 'CALZADOS FYC',
 'CANNON',
 'CANTINA LA 15',
 'CARNICOS Y ALIMENTOS',
 'CARPAS IKL ',
 'CEMENTOS SAN MARCOS',
 'CERAMICAS SAN LORENZO',
 'CERVALLE',
 'CIPA S.A ',
 'CIPA S.A.',
 'CM LADRILLERA SAN BENITO SAS',
 'COLHUELLAS',
 'COMFENALCO VALLE DELAGENTE',
 'COMPAÑIA OPERADORA PORTUARIA CAFETERA',
 'CONCIVILES',
 'CONTACTAMOS EQUIPOS',
 'CORPOASEO TOTAL SAS',
 'CORPOASEO TOTAL SAS ESP',
 'Camposanto metropolitano ',
 'Carnes Frías DCOSTA, SAS',
 'Cementos San Marcos',
 'Central Control ',
 'Cfc Cafarcol ',
 'Classic jeans',
 'Colhuellas ',
 'Comercializadora Inducascos SAS',
 'Comfenalco Valle',
 'Comfenalco Valle DeLaGente',
 'Comfenalco Valle DelaGente',
 'Compañia Operadora Portuaria Cafetera S.A',
 'Conciviles',
 'Creaciones Apice SAS',
 'Creaciones Apice Sas',
 'Creytex',
 'DIME',
 'DISCOLAB',
 'DOGGER',
 'Dmoda',
 'ECOPOSITIVA',
 'EL ZARZAL',
 'ESPEJOS SAS',
 'ESPUMAS SANTANDER',
 'Espejos SAS',
 'Espumas Santander SAS',
 'Etex',
 'Etex Colombia ',
 'Etex colombia ',
 'Extractora',
 'Extractora Central ',
 'Extractora la gloria',
 'FORSA',
 'FORSA sas',
 'FRANCORP',
 'FRITOMIX',
 'FUNDACIÓN E. SANTA ISABEL DE HUNGRÍA',
 'FYC CALZADO',
 'Forsa',
 'Francisco A Rocha Alvarado SAS',
 'Fresh produce',
 'Fundacion Zoologica de Cali',
 'Fundación Zoológica de Cali ',
 'GIROS Y FINANZAS',
 'GLF Colombia S.A.S.',
 'GRAVICON',
 'GRUPO KOPELLE SAS BIC',
 'Go Quito hotel',
 'Gravicon ',
 'Grupo Luz y Fuerza Colombia S.A.S.',
 'Gyplac',
 'ICOHARINAS',
 'INCOLMA',
 'INGENIERÍA Y ENCOFRADOS',
 'INVERSIONES EL DORADO',
 'INVERSIONES ELDORADO SAS',
 'INVERSIONES MARINA TTURISTICA SA',
 'INVERSIONES MARINA TURISTICA S.A.',
 'ITALCOL',
 'ITALCOL DE OCCIDENTE',
 'Incomineria S.A.S',
 'Industrias Cannon de Colombia ',
 'Industrias Cannon de Colombia S.A ',
 'Ingenieria y Encofrados ',
 'Integral de Empaques',
 'Inversiones Eldorado SAS',
 'Invesiones Eldorado SAS',
 'Italcol',
 'Italcol de occidente',
 'LA BIFERIA',
 'LA FABRICA DE LA FELICIDAD',
 'LA FABRICA DE LA FELICIDAD SAS',
 'LA FABRICA DE LA FELICIDAD SAS ',
 'LAO KAO ',
 'LAO KAO SA',
 'LLOREDA',
 'La Biferia',
 'La Biferia SA',
 'La Soberana',
 'Laminate packaging Colombia SAS ',
 'Lloreda SA',
 'MANITOBA',
 'MAS X MENOS',
 'MES GROUP S.A.S.',
 'MOLINOS EL YOPAL SAS',
 'MOLINOS VESGA',
 'MOLINOS VESGA ',
 'MOLINOS VESGA SAS ZOMAC',
 'MOLINOS YOPAL',
 'Manitoba sas',
 'Manitoba.sas',
 'Metecno Colombia',
 'Metecno de colombia S.A',
 'Mister Wings',
 'Molino El Lobo - Sede Bogota Centro',
 'Molino El Lobo S.A.',
 'MÁS X MENOS',
 'NEXTFOOD COLOMBIA SAS',
 'Nextfood Colombia',
 'OIT ',
 'OIT PRODUCTOS Y SOLUCIONES QUIMICAS SAS',
 'PALMEIRAS',
 'PLAST INNOVA S.A',
 'PLASTICOS TRUHER SA',
 'PROALPET SAS',
 'PRONAVICOLA',
 'PROQUIDENT',
 'PROQUIDENT ',
 'PROQUIDENT SAS',
 'Palmas oleaginosas Bucarelia',
 'Plast Innova',
 'Plast Innova SA',
 'Plasticos Truher',
 'Plásticos Rimax ',
 'Proalpet SAS',
 'Productos Alimenticios El Recreo SAS',
 'Productos alimenticios Dogger ',
 'Pronavicola SAS',
 'Propal',
 'Proquident ',
 'Provefabrica',
 'QUIMICOS DEL CAUCA',
 'Quimetales S.A.S E.S.P',
 'Quimetales SAS ESP',
 'Químicos del cauca',
 'RESTAURANTE MONSERRAT',
 'RIOPAILA',
 'RIOPAILA CASTILLA',
 'RIOPAILA CASTILLA S.A.',
 'Riopaila Castilla S.A',
 'Rymel Ingeniería',
 'SIMONIZ SA',
 'SISTEMAS DE INFORMACION EMPRESARIAL',
 'SOBERANA',
 'SOSTY',
 'SOSTY SERVICIO',
 'STANTON',
 'STUDIO F',
 'SUCDEN',
 'SUCDEN COLOMBIA SAS',
 'SUDEN',
 'SUPERMERCADO MAS POR MENOS ',
 'SUPERMERCADO MAS POR MENOS SAS',
 'SUPERMERCADOS MAS POR MENOS ',
 'SUPERMERCADOS MAS POR MENOS SAS',
 'SUPERTEX SAS',
 'Simoniz S.A',
 'Simoniz SA',
 'Sistemas de Información Empresarial S.A',
 'Smurfit Westrock',
 'Soplascol SAS',
 'Studiof ',
 'Superpack',
 'Supertex SA ',
 'TAKAMI SA',
 'TRANSPORTADORA LA PRENSA DEL VALLE S.A.S',
 'TRANSPRENSA',
 'Takami SA',
 'Transprensa',
 'Triada Ema',
 'Triada ema',
 'UNION DE ARROCEROS',
 'UNIQUIMICA',
 'UNIÓN DE ARROCEROS',
 'Unicentro',
 'VEOLIA',
 'Veolia',
 'Veolia servicios industriales ',
 'Virutex Ilko',
 'Wingo',
 'Yesenia Bernate',
 'ZULUAGA Y SOTO SAS',
 'administradora monserrate sas',
 'camposantometropolitano',
 'classic jeans',
 'colombina del cauca',
 'contactamos equipos',
 'corteaceros',
 'laminate',
 'laminate ',
 'supermercados mas por menos ',
 'supermercados mas por menos S.A']

In [13]:
# Revisión columna Cliente de maestro_cliente
df_maestro = pd.read_excel(config['sources']['maestro_clientes']['path'])
sorted(df_maestro['CLIENTE'].unique())

['ACCIONA',
 'ACEITES LA CRISTALINA',
 'ACRILAN',
 'ADIELA DE LOMBANA  S A',
 'AEROCALI',
 'AEROPUERTO DE BARRANQUILLA  O GRUPO AEROPORTUARIO DEL CARIBE',
 'AGRAF',
 'AGREGADOS Y MEZCLAS CACHIBI SAS',
 'AGRICOLA COLOMBIANA',
 'AGRICOLA COPAL',
 'AGRICOLAS',
 'AGRIVALDANI',
 'AGROCEREALES DEL VALLE',
 'AGROCOM',
 'AGRODEX',
 'AGROHIERRO',
 'AGROPECUARIA COPAL',
 'AGROPECUARIA DE OCCIDENTE',
 'AHUMADOS TOTO',
 'ALATURA MOBILIARIO',
 'ALDIMARK',
 'ALGRAFHER',
 'ALGRANEL',
 'ALIMENTOS BENAL',
 'ALMACENES SI',
 'ALMAGRARIO',
 'ALTOS DE PINARES',
 'AMBIOCOM',
 'AMORE GROUP',
 'ANCHERY',
 'ANDINO TECNOLOGÍA',
 'ANDRES CARNES DE RES',
 'ANTIOQUIA GOLD',
 'APIX',
 'APIX LOGISTICA ESPECIALIZADA',
 'APREHSI',
 'ARIGUANI',
 'ARQUIDIOCESIS DE CALI',
 'ARROCERA LA ESMERALDA',
 'ASISTENCIA TÉCNICA AGROINDUSTRIAL ',
 'AURALAC',
 'AVIAGEN',
 'AVIARIO NACIONAL',
 'AVICOLA O TAFUR',
 'AVICOLA SANTA RITA',
 'AVICOLA TRIPLE A ',
 'AYG INGENIERIA FUNDIMETAL',
 'BABÚ PALM',
 'BALL COLOMBIA LTDA',
 'BAZAR AMERICANO',
 'BEISBOL DE COLOMBIA S.A.S.',
 'BELANOVA',
 'BELLEZA EXPRESS - BIVIEN',
 'BERHLAN DE COLOMBIA',
 'BIFERIA',
 'BIG',
 'BIO D',
 'BIOCOSTA',
 'BLANCO Y NEGRO MASIVO',
 'BOSCOAL COMPAS',
 'BOSQUES DEL OESTE',
 'BRILLADORA EL DIAMANTE',
 'BUK EXHIBICIONES',
 'BURICA ',
 'BURICA SA',
 'CAFÉ QUINDÍO',
 'CALORCOL',
 'CALYPSO DEL CARIBE',
 'CANNON DE COLOMBIA',
 'CANTINA LA 15',
 'CAOBA',
 'CARNES FRIAS D COSTA',
 'CARNES Y DERIVADOS',
 'CARNICOS Y ALIMENTOS',
 'CARPAS IKL',
 'CARTAGUEÑA DE ASEO TOTAL ESP',
 'CARTONERA NACIONAL',
 'CARVAJAL CPP',
 'CELCO',
 'CEMENTOS SAN MARCOS',
 'CENTRA INGENIERIA SAS',
 'CENTRAL ABASTOS BUCARAMANGA',
 'CENTRAL CONTROL SAS',
 'CENTRO COMERCIAL PETECUY',
 'CENTRO INTERNACIONAL DE AGRICULTURA TROPICAL ',
 'CERAMICA SAN LORENZO',
 'CERROMATOSO',
 'CERVALLE',
 'CF QBICO',
 'CFC CAFARCOL S.A.S',
 'CHAMORRO PORTILLA',
 'CHIHUAHUA HOT DOG',
 'CHIPICHAPE',
 'CI FAMAR',
 'CI RTA DESING',
 'CIPA',
 'CLASSIC JEANS',
 'CLINICA DE OCCIDENTE ',
 'CLUB LA CAMPIÑA',
 'CLUB LOS CHILLOS',
 'COCINA JUSTA',
 'COLCAUCA',
 'COLCOBEANS SAS',
 'COLEGIO ALEMAN',
 'COLFACTORY',
 'COLHUELLAS',
 'COLOMBINA',
 'COMBARRANQUILLA',
 'COMECO',
 'COMFANDI',
 'COMFENALCO',
 'COMPAÑIA NACIONAL DE BEBIDAS',
 'COMPAÑIA OPERADORA PORTUARIA CAFETERA',
 'COMPAÑÍA CAFETERA LA MESETA',
 'CONCIVILES',
 'CONDOMIO INDUSTRIAL LA NUBIA II',
 'CONENCO',
 'CONFECCIONES CIELITO',
 'CONSTRUCCIONES INGENIERIA ',
 'CONTACTAMOS',
 'CORAZON Y AORTA SAS',
 'CORPORACION COLEGIO COLOMBO BRITANICO',
 'CORTEACEROS',
 'COSMOAGRO',
 'CREACIONES ÁPICE',
 'CREYTEX',
 'CRIPACK',
 'CRISTALES II',
 'CUMBIA HOUSE',
 'CUSTODIAR',
 'DE LA GRANJA ANTIOQUIA',
 'DE MODA SAS',
 'DIANA CORPORACIÓN S.A.S',
 'DIME',
 'DIMEL',
 'DIOCESIS DE PALMIRA',
 'DISANDINA',
 'DISCOLAB',
 'DOGGER',
 'DON MAIZ',
 'DROSERVICIO',
 'ECOPOSITIVA',
 'ECOPOSITIVA - CT',
 'EDIFICIO BELMONTE COLOMBINA',
 'EL CARNAL S.A.S',
 'EL TAMBOR',
 'EL TREBOL',
 'EL ZARZAL',
 'ELECTRÓNICA SAN NICOLAS',
 'ELÍAS ACOSTA',
 'EMBEBIDAS GLACIAL',
 'EMCALI',
 'EMPAQUES INDUSTRIALES',
 'ENTREPUES',
 'EQUISIS',
 'ESPEJOS S.A',
 'ESPUMAS SANTANDER',
 'ETEX',
 'EUCOL ',
 'EUROCERAMICAS',
 'EVACOL',
 'EXPANSION JL KOAJ',
 'EXPRESO BRASILIA',
 'EXTRACTORA CENTRAL',
 'EXTRACTORA VERDE DEL CASANARE',
 'EXTRUSIONES S.A',
 'FABRICA DE LA FELICIDAD',
 'FANALCA',
 'FARMAPLAST',
 'FERIAS Y EVENTOS',
 'FLEXPACK',
 'FLORES CAPIRO',
 'FOODHUB',
 'FORMACOL',
 'FORSA',
 'FOSFATOS DE BOYACÁ',
 'FRANCISCO ROCHA S.A.',
 'FRANCORP',
 'FRESH FRUITS & VEGETABLES',
 'FRESH PRODUCE',
 'FRITOMIX',
 'FRUGAL',
 'FRUTY GREEN PACKING SAS',
 'FULCRUM BIOMETRICS',
 'FUNDACION COLOMBINA- SOCIOS',
 'FUNDACIÓN EDUCATIVA SANTA ISABEL DE HUNGRIA',
 'FUNDACIÓN SARMIENTO',
 'FUNDACIÓN ZOOLÓGICA DE CALI',
 'FUNDICIONES DELIMA',
 'FUNDICIONES UNIVERSO SAS',
 'FUNERARIAS Y CAMPOSANTOS METROPOLITANO',
 'FYC CALZADO',
 'GENERAL RIGS SERVICE',
 'GERT',
 'GIROS Y FINANZAS',
 'GLF',
 'GLOBE AIR FUEL',
 'GOYAINCOL',
 'GRAVAS Y CONCRETOS',
 'GREEN SUPER FOOD',
 'GRUPO CBC',
 'GRUPO EMPRESARIAL PAPIS',
 'GRUPO EMPRESARIAL TASPA',
 'GRUPO EMPRESARIAL VARGAS DIAZ',
 'GUAICARAMO',
 'GYPLAC',
 'HACIENDA LA GLORIA',
 'HACIENDA SAS',
 'HOME CLUB PARAISO',
 'HOTEL CIUDAD DEL RIO',
 'HOTEL GRAN SIRENIS',
 'HOTEL HOSTERIA UZHUPUD',
 'HOTEL KLEIN',
 'HOTEL LA QUINTA QUITO',
 'HOTEL MARRIOTT',
 'HOTEL PLAYA PARAISO',
 'HOTEL SHERATON BOGOTA',
 'IBEASER',
 'IC PREFABRICADOS',
 'ICOHARINAS',
 'IE INGENIERIA Y ENCOFRADOS',
 'IGT INGENIERIA TOTAL',
 'IKON GROUP',
 'IMECOL S.A.',
 'IMEGRAF',
 'IMPORTACION TECNICA ESTUDIOS Y COMERCIAL SA',
 'IMPORTADORA OKLA',
 'IMPORTADORA UNICA',
 'IMPRESOS EL DIA',
 'INCAUCA PROVIDENCIA',
 'INCOLMA',
 'INCOMELEC',
 'INCOMINERIA',
 'INDUCASCOS',
 'INDULACTEOS',
 'INDUSTRIA DE LICORES DEL VALLE',
 'INFARTO',
 'ING CARMELITA',
 'ING LA CABAÑA',
 'ING PICHICHI',
 'ING RISARALDA',
 'ING SAN CARLOS',
 'INGENIO MAYAGUEZ',
 'INMACULADA GUADALUPE Y AMIGOS EN CIA SA',
 'INTEGRAFIC DE OCCIDENTE',
 'INTEGRAL DE EMPAQUES',
 'INTERGROUP ',
 'INVERCAFE CERRITOS',
 'INVERSIONES ELDORADO',
 'INVERSIONES VALLES VERDES SAS',
 'INVERSISA SAS (MR BONO)',
 'ISMOCOL',
 'ITALCOL',
 'ITALCOL PANAMÁ',
 'ITECO',
 'IZC',
 'J&J',
 'JARDIN PLAZA',
 'JINAN URISOT',
 'KAIKA',
 'KAL TIRE',
 'KARIBIK',
 'KINGSPAN - PANELMET',
 'KOPELLE',
 'KOS COLOMBIA SAS',
 'KUTY',
 'LA ECONOMÍA',
 'LA ESTRELLA SAS',
 'LA GRANJA DE TENJO',
 'LA NUBIA',
 'LACTEOS DEL CESAR',
 'LACTEOS RECREO',
 'LADRILLERA SAN BENITO',
 'LAKTOLAND',
 'LAMINAS Y EMPAQUES',
 'LAMINATE PACKAGING COLOMBIA SAS',
 'LAMITEXTIL',
 'LAOKAO',
 'LAS CASERITAS',
 'LATCO',
 'LATINCO',
 'LAVACLINICAS S.A.',
 'LIBRERIA NACIONAL',
 'LIMA- CONTRATISTAS',
 'LINCE COMERCIAL',
 'LINDA TEXTIL',
 'LINEA DATASCAN',
 'LLOREDA S.A',
 'LOGISTICA 361',
 'LOPESA INDUSTRIAL',
 'MAC DULCES',
 'MAINCO',
 'MAKROCOMPUTO',
 'MANITOBA',
 'MARES GROUP',
 'MARINA SANTA MARTA',
 'MASXMENOS',
 'MEDIPORT',
 'METECNO DE COLOMBIA',
 'METRO OPERACION',
 'MINECAR',
 'MISTER POLLO',
 'MM PACKAGING',
 'MOLINO EL LOBO',
 'MOLINOS EL YOPAL LTDA ',
 'MOLINOS VESGA',
 'MONTACARGAS AM Y M',
 'MORANGO',
 'MORDISCO',
 'MR WINGS',
 'MSIERRA FERRETEROS',
 'MULTIJUEGOS',
 'MULTISERVICIOS DE LA GUAJIRA',
 'MUNDO VERDE',
 'NATURAL HARVEST',
 'NAVCAR',
 'NEXSYS',
 'NEXT FOOD',
 'NOA HOTEL PIÑAS',
 'NOGAL',
 'NUTREE & CO SAS',
 'OCCIDENTAL DE PLASTICOS',
 'OCROVI',
 'ODECOPACK SAS',
 'ODINEC',
 'OIT PRODUCTOS QUIMICOS ',
 'OLEONORTE',
 'OLYMPO',
 'OMNICON S.A.',
 'ONECARIBE',
 'OPERADORA INTERNACIONAL AEROPUERTO DE CARTAGENA',
 'OPES - ESTACIONES DE SERVICIO',
 'OPLA - ITALCOL',
 'ORGANIZACIÓN BLESS',
 'PACIFIC SEA FOOD',
 'PALMAS MONTECARMELO',
 'PALMEIRAS COLOMBIA',
 'PANORAMA',
 'PETROWORKS',
 'PHARMETIQUE',
 'PIETRI',
 'PIZZA PICCOLO',
 'PLANTAR DE COLOMBIA',
 'PLAST INNOVA ',
 'PLASTICAUCHOS ',
 'PLASTICOS FAYCO',
 'PLASTICOS RIMAX',
 'PLASTICOS TRUHER',
 'PLATAFORMA COLOMBIA',
 'PLATAFORMA COLOMBIA ',
 'PLATAFORMA TECNOLÓGICA',
 'PLEXA ',
 'POLLO FIESTA',
 'PORCICULTORES APA',
 'PRADERA POTOSI',
 'PRAXEDIS DE ARTUNDUAGA ',
 'PROALPET',
 'PRODUCTOS TOMATICO',
 'PROEMPAQUES',
 'PROINGRA',
 'PRONAVICOLA',
 'PROQUIDENT',
 'PROTERRA',
 'PROVEFABRICAS',
 'PROVIGAS',
 'QBCO',
 'QUICK AND TASTY',
 'QUIMETALES',
 'QUÍMICOS DEL CAUCA',
 'RECREAR',
 'RECREATEC',
 'REPOSTERIA EL PORTAL',
 'RESTAURANTES MONSERRATE',
 'RIOPAILA CASTILLA',
 'ROMARCO',
 'ROY ALPHA',
 'ROYAL FILMS',
 'ROYAL FILMS PRELIQUIDACION',
 'RYMEL S.A.S',
 'SALOMON DURAN',
 'SAN MARCOS',
 'SANTA ANITA',
 'SANTIPOLLO SAS',
 'SAPUGA S.A.',
 'SAPUGA S.A. TRACING',
 'SCANSOURCE',
 'SECURITY SYSTEMS LTDA',
 'SENTRONIC',
 'SERO COLOMBIA',
 'SERVICIO PILOTAJE DE BUENAVENTURA ',
 'SERVICIOS DE ALIMENTACION LA VIANDA',
 'SERVIPAN LTDA',
 'SIESA',
 'SIMONIZ',
 'SIMPLEX',
 'SISTEMAS TELEINFORMATICOS',
 'SKINCO COLOMBIT',
 'SMURFIT KAPPA',
 'SOBERANA SAS',
 'SOCIEDAD DE MEJORAS PUBLICAS',
 'SOMEX',
 'SOPESA',
 'SOPLASCOL',
 'SOSTY SERVICIOS',
 'STANTON ',
 'STOCK KEEPER',
 'STUDIO F',
 'SUBAGAN',
 'SUCDEN',
 'SUCROAL',
 'SUMAFIN',
 'SUMINISTROS E IMPRESOS',
 'SUMMAR',
 'SUPERMERCADOS DELTA',
 'SUPERPACK',
 'SUPERTEX',
 'TAKAMI',
 'TECNICOS METALURGICOS',
 'TECNIFIL',
 'TECNIYALE',
 'TECNOQUÍMICAS',
 'TEXTILES MIRATEX',
 'TEYUNA FOODS',
 'THE PEOPLE COMPANY',
 'TIERRA ALTA',
 'TORRE DE CALI',
 'TOSTAO',
 'TRACING',
 'TRANSPORTADORA DE VALORES ATLAS',
 'TRANSPORTES CENTROVALLE SAS',
 'TRANSPRENSA',
 'TUBOPACK',
 'TUBOPLAST',
 'TUBOSA',
 'UNICENTRO',
 'UNILEVER',
 'UNIMETRO',
 'UNIPALMA',
 'UNIQUIMICA',
 'UNIVERSIDAD LIBRE',
 'UNIVERSIDAD SAN BUENAVENTURA',
 'UNIÓN DE ARROCEROS',
 'UNIÓN DE ARROCEROS TRACING',
 'URBANAS',
 'URBANIZACION LA ESPERANZA',
 'VALLAS Y AVISOS',
 'VALLE DE LA FERREIRA',
 'VALLESALUD IPS',
 'VEHIGRUPO',
 'VEOLIA',
 'VEOLIA CARTAGENA',
 'VEOLIA GUAJIRA',
 'VIALAMBRE',
 'VIAS Y EXPLANEACIONES ',
 'VICPAR',
 'VINOS DE LA CORTE Y CAODEL',
 'VINOS DEL RIO (MEGA TRADING)',
 'VIRUTEX ILKO',
 'VIVELL SAS',
 'WESTON ',
 'WINGO COPA AIRLINES',
 'Z GAMER',
 'ZULUAGA',
 'ZULUAGA Y SOTO']

In [ ]:
# Revisión columna Número de Ticket de encuesta_soporte
# Se identifican número de tickets sin la sigla del cliente o empresa, 
# Números con más de 4 digitos que no corresponden a un número de ticket
# Dado que esta columna será la llave a usar para unir ambas tablas, se debe realizar la corrección
sorted(encuesta_soporte_df['Número de Ticket'].unique())

[' TKMI-191 ',
 '110',
 '130',
 '14',
 '15',
 '16',
 '179',
 '185-186',
 '19',
 '20',
 '214',
 '216',
 '235',
 '3202601',
 '35',
 '72',
 '800133691',
 '817000705-5',
 '900.273.380-1 ',
 '91',
 'ACOL-1',
 'ACOL-2',
 'AES-18',
 'AG1-45 y AG1-46',
 'AG1-53',
 'AGD1-1',
 'AGO-69',
 'ALMGR-10 Reportes Mobiles',
 'ALMGR-3 ',
 'ALMGR-4 ',
 'ALMGR-5',
 'ALMGR-8 Novedad Registro Facial',
 'ALMGR-9',
 'ALMSI-105',
 'ALMSI-106',
 'ALMSI-108',
 'ALMSI-98',
 'ARC-24',
 'ARI-30',
 'ARI-31',
 'ARQ-8',
 'ASM1-30',
 'ATT-61',
 'Ago61',
 'BABU1-222',
 'BABU1-223',
 'BALL1-16',
 'BDC-66',
 'BDC-93',
 'BDC-95',
 'BE-23',
 'BE-24',
 'BE-26',
 'BE-33',
 'BFA-56',
 'BFA-67',
 'BFA-70',
 'BIOD1-10',
 'BL1-25',
 'BL1-29',
 'BL1-30',
 'BL1-31',
 'BL1-32',
 'BL1-33',
 'BL1-34',
 'BYN-22',
 'BYN-25',
 'BYN-27',
 'BYN-28',
 'BYN-29',
 'Bioc-27',
 'Biod1-11',
 'Biod1-8',
 'Bynm-18',
 'Bynm-21',
 'C15-15',
 'CAC-8',
 'CAFQ-31',
 'CAFQ-33',
 'CAFQ-34',
 'CAFQ-6',
 'CAFQ-8',
 'CAP- 2',
 'CAP-1',
 'CAP-3',
 'CDA-18',
 'CDA-19',
 'CDA-20',
 'CDA-21',
 'CDA-23',
 'CDA-24',
 'CFCOL-23',
 'CFCOL-27',
 'CFDC-5',
 'CFNC-18',
 'CFNC-19',
 'CFNC-20',
 'CFNC-24',
 'CFNC-26',
 'CFNC-30',
 'CH-10',
 'CH-12',
 'CH-6',
 'CH-7',
 'CIKL-15',
 'CIPA-50',
 'CIPA-68',
 'CJS-16',
 'CNN-44',
 'CNN-46',
 'CNN-49',
 'CNN-51',
 'CNTC1-13',
 'CONCV-17',
 'CONCV-19',
 'COPCSA1-27',
 'COPCSA1-32',
 'CSAGRO-23',
 'CSL-101',
 'CSM1-84',
 'CSM1-86 ',
 'CSM1-88 y 89',
 'CSSPG-84 ',
 'CTX-10',
 'CV-60',
 'CYA-29',
 'Cj14',
 'Cpp 18',
 'DEMODA-2',
 'DOGGER-9',
 'DSB-4',
 'ECOP1-17',
 'EPST1-23',
 'ESP-14',
 'ESP-15',
 'ESP12',
 'ETEX-34',
 'ETEX-38',
 'EXC1-19',
 'EZ-39',
 'Etex-24',
 'Etex-25',
 'Etex-50',
 'Etex-51',
 'FABRIFEL-4',
 'FABRIFEL-5',
 'FABRIFEL-6',
 'FCORP-59',
 'FCORP-62',
 'FESIH-1',
 'FMIX-12',
 'FRESH-6',
 'FRS-104 y FRS-105',
 'FRS-108',
 'FRS-112',
 'FRS-113',
 'FRS-114',
 'FRS-89',
 'FYC-19',
 'FYC-20',
 'FZC-2',
 'Fzc-3',
 'GLF1-54',
 'GLF1-55 ',
 'GLF1-56',
 'GVC-24',
 'GVC-30',
 'GYF-16',
 'HLG-13',
 'HLG-19',
 'HTKL1-1',
 'ICH-11',
 'IDC-28',
 'IDC-31',
 'IE-42',
 'IENC-2',
 'IENC-9',
 'ILKO 34',
 'INC-28',
 'INCM1-14',
 'INCT1-32',
 'INVED-100',
 'INVED-119',
 'INVED-96',
 'INVED-98',
 'ITL1-174',
 'ITL1-179',
 'ITL1-252',
 'ITL1-256',
 'ITL1-258',
 'ITL1-260',
 'ITL1-263',
 'ITL1-264',
 'ITL1-267',
 'JP1',
 'KPL-4',
 'LK-43',
 'LK-44',
 'LLRDA-1',
 'LLRDA-10',
 'LLRDA-13',
 'LLRDA-14',
 'LREC-14',
 'MEL 12',
 'MSM-6',
 'MSM-9',
 'MTB-24',
 'MTB-32',
 'MTB-36',
 'MTC-11',
 'MTC-12',
 'MVG-20',
 'MVG-53',
 'MVG-65',
 'MW-18',
 'MW-24',
 'MW-25',
 'MXM-58',
 'MXM-59',
 'MXM-63',
 'MXM52',
 'MXM53',
 'MXM55',
 'MXM56',
 'MY-105',
 'MY1-4',
 'MY1-5',
 'NEF-28',
 'No loce',
 'OIT1-23',
 'OIT1-30',
 'OIT1-31 ',
 'PALC1-7',
 'PLIV-4',
 'PLIV-5',
 'PLIV-9',
 'PLTH-28',
 'PPET-19',
 'PPET1-10',
 'PPET1-12 ',
 'PQR-37',
 'PQR52',
 'PRFV-14',
 'PROA-38',
 'PROA-43 y PROA-44',
 'PROA-50',
 'PRQ-58',
 'PRQ-64',
 'PRQ-83',
 'PRQ-85',
 'PSDI-1335',
 'Prq-66',
 'Prq-68',
 'Prq-84',
 'Prq-87',
 'Prq-88',
 'QDC-39',
 'QDC-44',
 'QDC-47',
 'QDC-48',
 'QUITAL-14',
 'QUITAL-15',
 'Qdc41',
 'RC-187',
 'RC-225',
 'RC-226',
 'RIM-51',
 'RIM-52',
 'RMT1-18',
 'RMT1-25',
 'RMT1-27',
 'RYMEL1-10',
 'Rc173',
 'SBN-28 y SBN-29',
 'SBN-51',
 'SBN-52',
 'SMIZ-10 ',
 'SMIZ-6',
 'SMIZ-9',
 'SMZ-14',
 'SPCL1-5 ',
 'SPP-12',
 'SPT-24',
 'STF - 131',
 'STF-120',
 'STT1-76',
 'STT1-77',
 'STT1-78',
 'STY1-16',
 'STY1-17',
 'STY1-51',
 'STY1-52',
 'STY1-53',
 'SUCDEN-106',
 'SUCDEN-107',
 'SUCDEN-79',
 'SUCDEN-81',
 'SUCDEN-82 REQUERIMIENTO',
 'Sin número',
 'Spt23',
 'TBP 31',
 'TBP-23',
 'TBP-24 ',
 'TKMI-200',
 'TKMI-201 ',
 'TKMI-202',
 'TRP-46',
 'TRP-54',
 'TRP-56',
 'Tbp 17',
 'Ticket N.º CAFQ-27',
 'Ticket N.º ZYS1-11',
 'Ticket N.º226',
 'Ticket N.º227',
 'Ticket N.º228',
 'Ticket N.º229',
 'Ticket SKC1-1 y SKCC1-16',
 'Tr 49',
 'UA-171',
 'UA-178',
 'UA-180',
 'UNQ-48',
 'VI-101',
 'VL-145',
 'VL-162',
 'Vl-69',
 'Wingo 10',
 'ZYS1-12',
 ']GLF1-58',
 'idc-32',
 'mel-14',
 'mxm47',
 'mxm52',
 'na']

In [ ]:
# Revisión columna Clave de incidencia de Jira
sorted(jira_df['Clave de incidencia'].unique())

['AASM-1',
 'AASM-2',
 'AASM-3',
 'AASM-4',
 'AC-10',
 'AC-11',
 'AC-8',
 'AC-9',
 'ACOL-1',
 'ACR-1',
 'ACR-10',
 'ACR-11',
 'ACR-12',
 'ACR-2',
 'ACR-6',
 'ACR-7',
 'ACR-9',
 'ACS2H-1',
 'ACS2H-2',
 'ACS2H-3',
 'ACS2H-4',
 'ACS2H-5',
 'ACS2H-6',
 'ACS2H-7',
 'ACS2H-8',
 'ACS2H-9',
 'ACX-10',
 'ACX-6',
 'ACX-7',
 'ACX-8',
 'ACX-9',
 'AES-10',
 'AES-11',
 'AES-12',
 'AES-13',
 'AES-14',
 'AES-15',
 'AES-16',
 'AES-17',
 'AES-18',
 'AES-19',
 'AES-20',
 'AES-21',
 'AES-22',
 'AES-23',
 'AES-24',
 'AES-25',
 'AES-26',
 'AES-27',
 'AES-29',
 'AES-3',
 'AES-30',
 'AES-4',
 'AES-5',
 'AES-6',
 'AES-7',
 'AES-8',
 'AES-9',
 'AG1-22',
 'AG1-23',
 'AG1-24',
 'AG1-25',
 'AG1-26',
 'AG1-27',
 'AG1-28',
 'AG1-29',
 'AG1-30',
 'AG1-31',
 'AG1-32',
 'AG1-33',
 'AG1-34',
 'AG1-35',
 'AG1-36',
 'AG1-38',
 'AG1-39',
 'AG1-40',
 'AG1-41',
 'AG1-42',
 'AG1-43',
 'AG1-44',
 'AG1-45',
 'AG1-46',
 'AG1-47',
 'AG1-48',
 'AG1-49',
 'AG1-50',
 'AG1-51',
 'AG1-52',
 'AG1-53',
 'AG1-54',
 'AG1-55',
 'AG1-56',
 'AG1-57',
 'AG1-58',
 'AG1-59',
 'AGD-24',
 'AGD-25',
 'AGD-26',
 'AGD-27',
 'AGD-28',
 'AGD-29',
 'AGD-30',
 'AGD-31',
 'AGD1-1',
 'AGDN-14',
 'AGDN-15',
 'AGDN-16',
 'AGH1-11',
 'AGH1-12',
 'AGHI1-11',
 'AGHI1-13',
 'AGHI1-14',
 'AGHI1-15',
 'AGHI1-16',
 'AGHI1-3',
 'AGHI1-4',
 'AGHI1-5',
 'AGHI1-6',
 'AGHI1-7',
 'AGHI1-8',
 'AGO-16',
 'AGO-17',
 'AGO-18',
 'AGO-19',
 'AGO-20',
 'AGO-21',
 'AGO-22',
 'AGO-24',
 'AGO-25',
 'AGO-26',
 'AGO-27',
 'AGO-28',
 'AGO-29',
 'AGO-30',
 'AGO-31',
 'AGO-32',
 'AGO-33',
 'AGO-34',
 'AGO-35',
 'AGO-36',
 'AGO-37',
 'AGO-38',
 'AGO-39',
 'AGO-40',
 'AGO-41',
 'AGO-42',
 'AGO-43',
 'AGO-44',
 'AGO-45',
 'AGO-46',
 'AGO-47',
 'AGO-48',
 'AGO-49',
 'AGO-50',
 'AGO-51',
 'AGO-52',
 'AGO-54',
 'AGO-56',
 'AGO-57',
 'AGO-58',
 'AGO-59',
 'AGO-60',
 'AGO-61',
 'AGO-62',
 'AGO-63',
 'AGO-64',
 'AGO-65',
 'AGO-66',
 'AGO-67',
 'AGO-68',
 'AGO-69',
 'AGO-70',
 'AGO-71',
 'AGO-72',
 'AGO-73',
 'AGRS-1',
 'AGRS-2',
 'AGRS-4',
 'AGRS-5',
 'AGV-10',
 'AGV-11',
 'AGV-12',
 'AGV-13',
 'AICDTMM-1',
 'AIS-1',
 'AIS-2',
 'AIS-3',
 'AIS-4',
 'AIS-5',
 'AIS-6',
 'AIS-7',
 'AIS-8',
 'AIS-9',
 'ALC-40',
 'ALC-41',
 'ALC-42',
 'ALC-43',
 'ALC-44',
 'ALC-45',
 'ALC-46',
 'ALC-47',
 'ALC-48',
 'ALC-49',
 'ALC-50',
 'ALC-51',
 'ALC-52',
 'ALC-53',
 'ALC-54',
 'ALC-55',
 'ALC-56',
 'ALC-57',
 'ALC1-1',
 'ALMGR-1',
 'ALMGR-10',
 'ALMGR-11',
 'ALMGR-2',
 'ALMGR-3',
 'ALMGR-4',
 'ALMGR-5',
 'ALMGR-6',
 'ALMGR-7',
 'ALMGR-8',
 'ALMGR-9',
 'ALMSI-100',
 'ALMSI-101',
 'ALMSI-103',
 'ALMSI-104',
 'ALMSI-105',
 'ALMSI-19',
 'ALMSI-20',
 'ALMSI-21',
 'ALMSI-22',
 'ALMSI-23',
 'ALMSI-24',
 'ALMSI-25',
 'ALMSI-26',
 'ALMSI-27',
 'ALMSI-28',
 'ALMSI-29',
 'ALMSI-30',
 'ALMSI-31',
 'ALMSI-32',
 'ALMSI-33',
 'ALMSI-34',
 'ALMSI-35',
 'ALMSI-36',
 'ALMSI-37',
 'ALMSI-38',
 'ALMSI-39',
 'ALMSI-40',
 'ALMSI-41',
 'ALMSI-42',
 'ALMSI-44',
 'ALMSI-45',
 'ALMSI-46',
 'ALMSI-47',
 'ALMSI-48',
 'ALMSI-49',
 'ALMSI-50',
 'ALMSI-51',
 'ALMSI-52',
 'ALMSI-53',
 'ALMSI-54',
 'ALMSI-55',
 'ALMSI-56',
 'ALMSI-57',
 'ALMSI-58',
 'ALMSI-59',
 'ALMSI-60',
 'ALMSI-61',
 'ALMSI-62',
 'ALMSI-63',
 'ALMSI-64',
 'ALMSI-65',
 'ALMSI-66',
 'ALMSI-67',
 'ALMSI-68',
 'ALMSI-69',
 'ALMSI-70',
 'ALMSI-71',
 'ALMSI-72',
 'ALMSI-73',
 'ALMSI-74',
 'ALMSI-75',
 'ALMSI-76',
 'ALMSI-78',
 'ALMSI-79',
 'ALMSI-80',
 'ALMSI-81',
 'ALMSI-82',
 'ALMSI-83',
 'ALMSI-84',
 'ALMSI-85',
 'ALMSI-86',
 'ALMSI-87',
 'ALMSI-88',
 'ALMSI-89',
 'ALMSI-90',
 'ALMSI-91',
 'ALMSI-92',
 'ALMSI-93',
 'ALMSI-94',
 'ALMSI-95',
 'ALMSI-96',
 'ALMSI-97',
 'ALMSI-98',
 'ALMSI-99',
 'AMBM-11',
 'AMBM-12',
 'AMBM1-1',
 'AMBM1-2',
 'AMBM1-3',
 'AMBM1-4',
 'AMBM1-5',
 'AMBM1-6',
 'AMBM1-7',
 'AMBM1-8',
 'AMBM1-9',
 'ARC-1',
 'ARC-10',
 'ARC-11',
 'ARC-12',
 'ARC-13',
 'ARC-14',
 'ARC-15',
 'ARC-16',
 'ARC-17',
 'ARC-18',
 'ARC-19',
 'ARC-2',
 'ARC-20',
 'ARC-21',
 'ARC-22',
 'ARC-23',
 'ARC-24',
 'ARC-3',
 'ARC-4',
 'ARC-5',
 'ARC-6',
 'ARC-7',
 'ARC-8',
 'ARC-9',
 'ARI-12',
 'ARI-13',
 'ARI-15',
 'ARI-16',
 'ARI-17',
 'ARI-18',
 'ARI-19',
 'ARI-21',
 'ARI-22',
 'ARI-23',
 'ARI-24',
 'ARI-25',
 'ARI-26',
 'ARI-27',
 'ARI-28',
 'ARI-29',
 'ARQ-2',
 'ARQ-3',
 'ARQ-4',
 'ARQ-5',
 'ARQ-6',
 'ARQ-7',
 'ARQ-8',
 'ARQ-9',
 'ASM-32',
 'ASM-33',
 'ASM-34',
 'ASM-35',
 'ASM1-10',
 'ASM1-11',
 'ASM1-12',
 'ASM1-13',
 'ASM1-14',
 'ASM1-15',
 'ASM1-16',
 'ASM1-17',
 'ASM1-18',
 'ASM1-19',
 'ASM1-20',
 'ASM1-21',
 'ASM1-22',
 'ASM1-23',
 'ASM1-24',
 'ASM1-25',
 'ASM1-26',
 'ASM1-27',
 'ASM1-28',
 'ASM1-29',
 'ASM1-30',
 'ASM1-31',
 'ASM1-32',
 'ASM1-33',
 'ASM1-34',
 'ASM1-4',
 'ASM1-5',
 'ASM1-6',
 'ASM1-7',
 'ASM1-8',
 'ASM1-9',
 'ATT-10',
 'ATT-12',
 'ATT-13',
 'ATT-14',
 'ATT-15',
 'ATT-16',
 'ATT-17',
 'ATT-18',
 'ATT-19',
 'ATT-20',
 'ATT-22',
 'ATT-23',
 'ATT-24',
 'ATT-25',
 'ATT-26',
 'ATT-27',
 'ATT-28',
 'ATT-29',
 'ATT-30',
 'ATT-31',
 'ATT-32',
 'ATT-33',
 'ATT-34',
 'ATT-35',
 'ATT-36',
 'ATT-37',
 'ATT-38',
 'ATT-39',
 'ATT-40',
 'ATT-41',
 'ATT-42',
 'ATT-43',
 'ATT-44',
 'ATT-47',
 'ATT-48',
 'ATT-49',
 'ATT-51',
 'ATT-53',
 'ATT-55',
 'ATT-57',
 'ATT-58',
 'ATT-59',
 'ATT-60',
 'ATT-61',
 'ATT-62',
 'ATT-63',
 'ATT-64',
 'ATT-65',
 'ATT-66',
 'ATT-67',
 'ATT-68',
 'ATT-70',
 'ATT-71',
 'ATT-72',
 'ATT-73',
 'ATT-74',
 'ATT-75',
 'ATT-76',
 'ATT-77',
 'ATT-78',
 'ATT-79',
 'AVGN-32',
 'AVGN-33',
 'AVGN-34',
 'AYG-3',
 'AYG-4',
 'BABU-80',
 'BABU-81',
 'BABU-82',
 'BABU-83',
 'BABU-84',
 'BABU-85',
 'BABU-86',
 'BABU-87',
 'BABU1-100',
 'BABU1-101',
 'BABU1-102',
 'BABU1-103',
 'BABU1-104',
 'BABU1-105',
 'BABU1-107',
 'BABU1-108',
 'BABU1-109',
 'BABU1-110',
 'BABU1-111',
 'BABU1-112',
 'BABU1-113',
 'BABU1-114',
 'BABU1-115',
 'BABU1-116',
 'BABU1-117',
 'BABU1-118',
 'BABU1-119',
 'BABU1-120',
 'BABU1-121',
 'BABU1-122',
 'BABU1-123',
 'BABU1-124',
 'BABU1-125',
 'BABU1-126',
 'BABU1-127',
 'BABU1-128',
 'BABU1-129',
 'BABU1-130',
 'BABU1-131',
 'BABU1-132',
 'BABU1-133',
 'BABU1-134',
 'BABU1-135',
 'BABU1-136',
 'BABU1-137',
 'BABU1-138',
 'BABU1-139',
 'BABU1-140',
 'BABU1-141',
 'BABU1-142',
 'BABU1-143',
 'BABU1-144',
 'BABU1-145',
 'BABU1-146',
 'BABU1-147',
 'BABU1-148',
 'BABU1-149',
 'BABU1-150',
 'BABU1-151',
 'BABU1-152',
 'BABU1-153',
 'BABU1-154',
 'BABU1-155',
 'BABU1-156',
 'BABU1-157',
 'BABU1-158',
 'BABU1-159',
 'BABU1-160',
 'BABU1-161',
 'BABU1-162',
 'BABU1-163',
 'BABU1-164',
 'BABU1-165',
 'BABU1-166',
 'BABU1-167',
 'BABU1-168',
 'BABU1-169',
 'BABU1-170',
 'BABU1-171',
 'BABU1-172',
 'BABU1-173',
 'BABU1-174',
 'BABU1-175',
 'BABU1-176',
 'BABU1-177',
 'BABU1-178',
 'BABU1-179',
 'BABU1-180',
 'BABU1-181',
 'BABU1-182',
 'BABU1-183',
 'BABU1-184',
 'BABU1-185',
 'BABU1-186',
 'BABU1-187',
 'BABU1-188',
 'BABU1-189',
 'BABU1-190',
 'BABU1-191',
 'BABU1-192',
 'BABU1-193',
 'BABU1-194',
 'BABU1-195',
 'BABU1-196',
 'BABU1-197',
 'BABU1-198',
 'BABU1-199',
 'BABU1-200',
 'BABU1-201',
 'BABU1-202',
 'BABU1-203',
 'BABU1-204',
 'BABU1-205',
 'BABU1-206',
 'BABU1-207',
 'BABU1-208',
 'BABU1-209',
 'BABU1-210',
 'BABU1-211',
 'BABU1-212',
 'BABU1-213',
 'BABU1-214',
 'BABU1-215',
 'BABU1-216',
 'BABU1-217',
 'BABU1-218',
 'BABU1-219',
 'BABU1-220',
 'BABU1-221',
 'BABU1-222',
 'BABU1-223',
 'BABU1-224',
 'BABU1-225',
 'BABU1-226',
 'BABU1-227',
 'BABU1-228',
 'BABU1-229',
 'BABU1-230',
 'BABU1-231',
 'BABU1-232',
 'BABU1-233',
 'BABU1-234',
 'BABU1-235',
 'BABU1-236',
 'BABU1-237',
 'BABU1-238',
 'BABU1-239',
 'BABU1-240',
 'BABU1-241',
 'BABU1-242',
 'BABU1-243',
 'BABU1-244',
 'BABU1-245',
 'BABU1-246',
 'BABU1-247',
 'BABU1-248',
 'BABU1-249',
 'BABU1-250',
 'BABU1-251',
 'BABU1-252',
 'BABU1-253',
 'BABU1-254',
 'BABU1-255',
 'BABU1-256',
 'BABU1-257',
 'BABU1-258',
 'BABU1-259',
 'BABU1-260',
 'BABU1-261',
 'BABU1-262',
 'BABU1-263',
 'BABU1-264',
 'BABU1-265',
 'BABU1-266',
 'BABU1-267',
 'BABU1-268',
 'BABU1-269',
 'BABU1-270',
 'BABU1-271',
 'BABU1-272',
 'BABU1-273',
 'BABU1-30',
 'BABU1-31',
 'BABU1-32',
 'BABU1-34',
 'BABU1-35',
 'BABU1-36',
 'BABU1-37',
 'BABU1-38',
 'BABU1-39',
 'BABU1-40',
 'BABU1-41',
 'BABU1-42',
 'BABU1-43',
 'BABU1-44',
 'BABU1-45',
 'BABU1-46',
 'BABU1-47',
 'BABU1-48',
 'BABU1-49',
 'BABU1-50',
 'BABU1-51',
 'BABU1-52',
 'BABU1-53',
 'BABU1-54',
 'BABU1-55',
 'BABU1-56',
 'BABU1-57',
 'BABU1-58',
 'BABU1-59',
 'BABU1-60',
 'BABU1-61',
 'BABU1-62',
 'BABU1-63',
 'BABU1-64',
 'BABU1-65',
 'BABU1-66',
 'BABU1-67',
 'BABU1-68',
 'BABU1-69',
 'BABU1-70',
 'BABU1-71',
 'BABU1-72',
 'BABU1-73',
 'BABU1-74',
 'BABU1-75',
 'BABU1-76',
 'BABU1-77',
 'BABU1-78',
 'BABU1-79',
 'BABU1-80',
 'BABU1-81',
 'BABU1-82',
 'BABU1-83',
 'BABU1-84',
 'BABU1-85',
 'BABU1-86',
 'BABU1-87',
 'BABU1-88',
 'BABU1-89',
 'BABU1-90',
 'BABU1-91',
 'BABU1-92',
 'BABU1-93',
 'BABU1-94',
 'BABU1-95',
 'BABU1-96',
 'BABU1-97',
 'BABU1-98',
 'BABU1-99',
 'BABUCS-6',
 'BABUCS-7',
 'BABUCS-8',
 'BABUCS-9',
 'BALL1-1',
 'BALL1-10',
 'BALL1-12',
 'BALL1-13',
 'BALL1-14',
 'BALL1-15',
 'BALL1-16',
 'BALL1-17',
 'BALL1-3',
 'BALL1-4',
 'BALL1-5',
 'BALL1-6',
 'BALL1-7',
 'BAQ-3',
 'BAQ-4',
 'BAQ-5',
 'BDC-21',
 'BDC-22',
 'BDC-23',
 'BDC-24',
 'BDC-25',
 'BDC-26',
 'BDC-27',
 'BDC-28',
 'BDC-29',
 'BDC-30',
 'BDC-31',
 'BDC-32',
 'BDC-33',
 'BDC-34',
 'BDC-35',
 'BDC-36',
 'BDC-37',
 'BDC-38',
 'BDC-39',
 'BDC-40',
 'BDC-41',
 'BDC-42',
 'BDC-43',
 'BDC-44',
 'BDC-45',
 'BDC-46',
 'BDC-47',
 'BDC-48',
 'BDC-49',
 'BDC-50',
 'BDC-51',
 'BDC-52',
 'BDC-53',
 'BDC-54',
 'BDC-55',
 'BDC-56',
 'BDC-57',
 'BDC-58',
 'BDC-59',
 'BDC-60',
 'BDC-61',
 'BDC-62',
 'BDC-63',
 'BDC-64',
 'BDC-65',
 'BDC-66',
 'BDC-67',
 'BDC-68',
 'BDC-69',
 'BDC-70',
 'BDC-71',
 'BDC-72',
 'BDC-73',
 'BDC-75',
 'BDC-76',
 'BDC-77',
 'BDC-78',
 'BDC-79',
 'BDC-80',
 'BDC-81',
 'BDC-82',
 'BDC-83',
 'BDC-84',
 'BDC-85',
 'BDC-86',
 'BDC-90',
 'BDC-91',
 'BDC-92',
 'BDC-93',
 'BDC-94',
 'BE-10',
 'BE-11',
 'BE-12',
 'BE-13',
 'BE-14',
 'BE-15',
 'BE-16',
 'BE-17',
 'BE-18',
 'BE-20',
 'BE-21',
 'BE-22',
 'BE-23',
 'BE-24',
 'BE-25',
 'BE-26',
 'BE-27',
 'BE-28',
 'BE-29',
 'BE-30',
 'BE-31',
 'BE-32',
 'BE-33',
 'BE-34',
 'BE-36',
 'BE-9',
 'BFA-16',
 'BFA-17',
 'BFA-18',
 'BFA-19',
 'BFA-20',
 'BFA-21',
 'BFA-22',
 'BFA-23',
 'BFA-24',
 'BFA-25',
 'BFA-26',
 'BFA-27',
 'BFA-28',
 'BFA-29',
 'BFA-30',
 'BFA-31',
 'BFA-32',
 'BFA-33',
 'BFA-34',
 'BFA-35',
 'BFA-36',
 'BFA-37',
 'BFA-38',
 'BFA-39',
 'BFA-40',
 'BFA-41',
 'BFA-42',
 'BFA-43',
 'BFA-44',
 'BFA-45',
 'BFA-46',
 'BFA-47',
 'BFA-48',
 'BFA-49',
 'BFA-50',
 'BFA-51',
 'BFA-52',
 'BFA-54',
 'BFA-55',
 'BFA-56',
 'BFA-57',
 'BFA-58',
 'BFA-59',
 'BFA-60',
 'BFA-61',
 'BFA-62',
 'BFA-63',
 'BFA-64',
 'BFA-66',
 'BFA-67',
 'BFA-68',
 'BFA-69',
 'BIG-10',
 'BIG-11',
 'BIG-12',
 'BIG-13',
 'BIG-15',
 'BIG-2',
 'BIG-3',
 'BIG-4',
 'BIG-5',
 'BIG-6',
 'BIG-7',
 'BIG-8',
 'BIG-9',
 'BIOC-10',
 'BIOC-11',
 'BIOC-12',
 'BIOC-13',
 'BIOC-14',
 'BIOC-15',
 'BIOC-16',
 'BIOC-17',
 'BIOC-18',
 'BIOC-19',
 'BIOC-20',
 'BIOC-21',
 'BIOC-22',
 'BIOC-23',
 'BIOC-25',
 'BIOC-26',
 'BIOC-27',
 'BIOC-28',
 'BIOC-29',
 'BIOC-30',
 'BIOC-31',
 'BIOC-32',
 'BIOC-33',
 'BIOC-34',
 'BIOC-35',
 'BIOC-36',
 'BIOC-37',
 'BIOC-38',
 'BIOC-39',
 'BIOC-40',
 'BIOC-41',
 'BIOC-42',
 'BIOD1-1',
 'BIOD1-10',
 'BIOD1-11',
 'BIOD1-12',
 'BIOD1-13',
 'BIOD1-2',
 'BIOD1-3',
 'BIOD1-4',
 'BIOD1-5',
 'BIOD1-6',
 'BIOD1-7',
 'BIOD1-8',
 'BIOD1-9',
 'BIS-1',
 'BIS-10',
 'BIS-2',
 'BIS-3',
 'BIS-4',
 'BIS-5',
 'BIS-6',
 'BIS-7',
 'BIS-8',
 'BIS-9',
 'BL1-10',
 'BL1-11',
 'BL1-12',
 'BL1-13',
 'BL1-14',
 'BL1-15',
 'BL1-16',
 'BL1-17',
 'BL1-18',
 'BL1-19',
 'BL1-20',
 'BL1-21',
 'BL1-22',
 'BL1-23',
 'BL1-24',
 'BL1-25',
 'BL1-26',
 'BL1-27',
 'BL1-28',
 'BL1-29',
 'BL1-30',
 'BL1-31',
 'BL1-32',
 'BL1-33',
 'BL1-5',
 'BL1-6',
 'BL1-7',
 'BL1-8',
 'BL1-9',
 'BRD-17',
 'BRD-18',
 'BRD-19',
 'BRD-20',
 'BRD-21',
 'BRD-22',
 'BRD-23',
 'BRD-24',
 'BRD-25',
 'BRD-26',
 'BRD-27',
 'BYN-11',
 'BYN-12',
 'BYN-13',
 'BYN-14',
 'BYN-15',
 'BYN-16',
 'BYN-17',
 ...]

In [12]:
#Prueba de código para estandarizar nombres de compañias y corregir número de tickets de encuesta_soporte
import re
import pandas as pd
from rapidfuzz import process, fuzz

# Carga de archivos
df_encuesta = pd.read_excel(config['sources']['encuesta_soporte']['path'])
df_maestro = pd.read_excel(config['sources']['maestro_clientes']['path']) #maestro con los nombres de las compañias

#Cambio nombre de columna para facilitar el código
df_encuesta = df_encuesta.rename(columns={'Nombre de la Compañía': 'NOMBRE_COMPANIA'})

# --- FUNCIÓN DE LIMPIEZA ---
def limpiar_texto(texto):
    if pd.isna(texto):  #Si el valor es nulo, devuelve un texto vacío
        return "" 
    txt = str(texto).upper().strip() #Convierte el texto a mayúscula y elimina espacios innecesarios

    # Quitamos tildes para que 'QUINDIO' y 'QUÍNDIO' sean idénticos
    replacements = (
        ("Á", "A"),
        ("É", "E"),
        ("Í", "I"),
        ("Ó", "O"),
        ("Ú", "U"),
    )
    for a, b in replacements:
        txt = txt.replace(a, b)

    # Quitamos puntos, comas, caracteres especiales y múltiples espacios seguidos usando expresiones regulares
    txt = re.sub(r"[.,\-_/]", " ", txt)
    txt = re.sub(r"\s+", " ", txt).strip()
    return txt


# Aplicamos la limpieza a las columnas NOMBRE_COMPANIA y CLIENTE de df_encuesta y df_maestro
df_encuesta["NOMBRE_COMPANIA_LIMPIO"] = df_encuesta[
    "NOMBRE_COMPANIA"
].apply(limpiar_texto)

df_maestro["CLIENTE_LIMPIO"] = df_maestro["CLIENTE"].apply(
    limpiar_texto
)

#Mapeo para recuperar el formato exacto del maestro al final (se crea un diccionario con el nombre original y el nombre limpio)
mapeo_original = pd.Series(
    df_maestro["CLIENTE"].values, index=df_maestro["CLIENTE_LIMPIO"]
).to_dict()


#Función de búsqueda de clientes: 
#Aquí se realiza el match entre el nombre ingresado en la encuesta y la lista oficial de clientes en el archivo maestro
def buscar_cliente_maestro(nombre_encuesta, opciones_maestro):
    if not nombre_encuesta or nombre_encuesta == "":    #Si el campo llega vacio retonar None
        return None, None
    #Filtra el maestro eliminando valores nulos o vacíos y extrae una lista de nombres de empresas únicos.
    lista_opciones = (
        opciones_maestro.replace("", None).dropna().unique().tolist() 
    )

    if not lista_opciones:  #Si no hay empresas para comparar, retorna "SIN COINCIDENCIA SEGURA", None.
        return "SIN COINCIDENCIA SEGURA", None

    #Usamos token_set_ratio de RapidFuzz para encontrar la empresa del maestro más parecida
    #token_set_ratio ignora el orden de las palabras e ignora palabras repetidas (se busca un 100% de similitud de "CAFÉ QUINDÍO" con "CAFÉ QUINDÍO S.A.S.")
    resultado = process.extractOne(
        str(nombre_encuesta), lista_opciones, scorer=fuzz.token_set_ratio
    )

    if resultado:
        mejor_coincidencia, puntaje, _ = resultado

        # --- VALIDACIÓN ADICIONAL DE SEGURIDAD (Control de falsos positivos) ---
        # Si el puntaje es alto por palabras comunes como "COLOMBIA", se hace un segundo filtro.
        # Quitamos palabras corporativas de control SOLO para verificar falsos positivos 
        # como Grupo Luz y Fuerza Colombia vs Sero Colombia (estos dos nombres los estaba relacionando anteriormente)
        palabras_ruido = r"\b(S\.?A\.?S\.?|S\.?A\.?|LTDA\.?|LTD\.?|GRUPOS?|COLOMBIA)\b"
        txt1_check = re.sub(palabras_ruido, "", nombre_encuesta).strip()
        txt2_check = re.sub(
            palabras_ruido, "", mejor_coincidencia
        ).strip()

        # Si al quitar el ruido la palabra principal no tiene NADA en común (como Grupo Luz y Fuerza vs Sero)
        # el token_set_ratio de control caerá drásticamente.
        puntaje_control = fuzz.token_set_ratio(txt1_check, txt2_check)

        # Regla de aceptación:
        # Se acepta si el puntaje original es mayor o igual al 85%  y el puntaje de control es de mayor o igual al 60%
        # Y se recahaza si el puntaje de control cae por debajo de 60% (como Luz y Fuerza vs Sero)
        if puntaje >= 85 and puntaje_control >= 60:
            return mapeo_original.get(mejor_coincidencia), round(
                puntaje, 2
            )

    return "SIN COINCIDENCIA SEGURA", None


#Ejecución del proceso:
#Se aplica la función buscar_cliente_maestro fila por fila a la columna NOMBRE_COMPANIA_LIMPIO de la encuesta_soporte
#lambda es una función rápida para pasarle a la función buscar_cliente_maestro el nombre de cada empresa (para cada celda x de esa columna)
print("Aplicando función buscar_cliente_maestro")

resultados = df_encuesta["NOMBRE_COMPANIA_LIMPIO"].apply(
    lambda x: pd.Series(
        buscar_cliente_maestro(x, df_maestro["CLIENTE_LIMPIO"])
    )
)

df_encuesta[["CLIENTE_MAESTRO_ENCONTRADO", "PORCENTAJE_CERTEZA"]] = (
    resultados
)

# Limpiar columna temporal antes de guardar
df_encuesta = df_encuesta.drop(columns=["NOMBRE_COMPANIA_LIMPIO"])

#LIMPIEZA DE TICKETS
# Validar y corregir formato de la columna ticket
if "Número de Ticket" in df_encuesta.columns:

    def formatear_ticket(val):
        # Manejo de nulos: Si el valor es nulo
        if pd.isna(val):
            return np.nan

        val_str = str(val).strip().upper()

        # Si contiene textos equivalentes a vacío
        if val_str in ["NAN", "NAT", "<NA>", ""]:
            return np.nan

        # Quitar decimales flotantes (ej. 123.0 -> 123)
        if val_str.endswith(".0"):
            val_str = val_str[:-2]

        # CASO 1 LIMPIEZA TICKETS: Formato estricto LETRAS-NÚMEROS (ej. ALMGR-10 REPORTES, GLF1-58)
        # Busca un prefijo de letras (con números opcionales intermedios como GLF1) y luego el bloque numérico final
        match_prefijo = re.search(r"\b([A-Z]+[0-9]*)-?([0-9]+)\b", val_str)

        if match_prefijo:
            letras = match_prefijo.group(1)
            numeros = match_prefijo.group(2)

            # REGLA: Si el número tiene más de 4 dígitos, es inválido. Los números de un id ticket no superan los 4 digitos.
            if len(numeros) > 4:
                return np.nan

            # Si la palabra inicial es genérica (como TICKET), se reemplaza por el prefijo temporal NAN (NAN-número)
            if letras in ["TICKET", "TICKETS", "N", "NO", "NUMERO"]:
                return f"NAN-{numeros}"

            return f"{letras}-{numeros}"

        # CASO 2 LIMPIEZA TICKETS: Solo números o palabras genéricas con números sueltos (ej. 123, "TICKET 123")
        # Se extrae todos los bloques numéricos del string
        bloques_numericos = re.findall(r"\d+", val_str)

        if bloques_numericos:
            # Tomamos el primer bloque numérico que encuentre
            primer_numero = bloques_numericos[0]

            # REGLA: Si supera los 4 dígitos se descarta, ya que los números de un id ticket no superan los 4 digitos
            if len(primer_numero) > 4:
                return np.nan

            return f"NAN-{primer_numero}" # si el número es valido lo coloca como NAN-número

        # Si el texto no tiene números (ej. "SIN NÚMERO", "NO LOCE"). 
        return np.nan

    # Aplicar el formateo a la columna
    df_encuesta["Número de Ticket"] = df_encuesta["Número de Ticket"].apply(
        formatear_ticket
    )
# El siguiente bloque se ejecuta después de haber formateado 'Número de Ticket' y 'CLIENTE_MAESTRO_ENCONTRADO'
# Debido a que en el bloque anterior muchos tickets quedaron grabados con el prefijo temporal "NAN-número",
# el siguiente bloque busca corregirlos cruzando la información con el maestro de clientes, para colocarle la sigla correcta al ticket
if "Número de Ticket" in df_encuesta.columns:

    print(
        "Buscando siglas correspondientes para tickets genéricos (NAN-número)..."
    )

    # Crea un diccionario de mapeo rápido entre el CLIENTE y su SIGLA desde el maestro
    # Elimina duplicados y se asegura que no haya valores nulos en el maestro antes de crear el diccionario
    df_maestro_limpio = df_maestro.dropna(subset=["CLIENTE", "SIGLAS"])
    mapeo_siglas = pd.Series(
        df_maestro_limpio["SIGLAS"].values,
        index=df_maestro_limpio["CLIENTE"],
    ).to_dict()

    # Función interna para procesar fila por fila de la encuesta
    def reemplazar_nan_por_sigla(fila):
        ticket = str(fila["Número de Ticket"])

        # Identificar si el ticket está catalogado bajo el patrón "NAN-número"
        if ticket.startswith("NAN-"):
            # Extraemos la parte numérica (ej: de 'NAN-123' tomamos '123')
            numero_ticket = ticket.split("-")[1]

            # Obtenemos el nombre del cliente real que encontramos previamente con fuzzy
            cliente_encontrado = fila.get("CLIENTE_MAESTRO_ENCONTRADO")

            # Si encontramos un cliente válido en el maestro para esta fila
            if (
                pd.notna(cliente_encontrado)
                and cliente_encontrado != "SIN COINCIDENCIA SEGURA"
            ):
                # Buscamos la sigla en nuestro diccionario de mapeo
                sigla = mapeo_siglas.get(cliente_encontrado)

                # Si el cliente tiene una sigla asignada en el maestro, estructuramos el nuevo ticket
                if pd.notna(sigla) and str(sigla).strip() != "":
                    return f"{str(sigla).strip().upper()}-{numero_ticket}"

        # Si no era un ticket NAN o no se encontró sigla, se deja el valor original
        return fila["Número de Ticket"]

    # Aplicar la función a lo largo del dataframe (fila por fila)
    df_encuesta["Número de Ticket"] = df_encuesta.apply(
        reemplazar_nan_por_sigla, axis=1
    )

    print("¡Reemplazo de siglas completado con éxito!")

#Guardar archivo final
archivo_salida = "notebooks/RESULTADO_COMPANIAS_TICKETS.xlsx"
df_encuesta.to_excel(archivo_salida, index=False)

print(f"¡Optimización de tickets completada! Archivo final: {archivo_salida}")

Aplicando función buscar_cliente_maestro
Buscando siglas correspondientes para tickets genéricos (NAN-número)...
¡Reemplazo de siglas completado con éxito!
¡Optimización de tickets completada! Archivo final: notebooks/RESULTADO_COMPANIAS_TICKETS.xlsx